export const orderData = [
  {
    id: "GD-2048",
    customerName: "Karan Chandra Kothari",
    customerEmail: "kotharikaran07@gmail.com",
    customerPhone: "+91 92679 33722",
    productName: "Premium Leather Jacket",
    productCategory: "Fashion",
    quantity: 1,
    orderDate: "2026-06-01",
    deliveryDate: "2026-06-07",
    shippingMethod: "Express Delivery",
    paymentMethod: "Credit Card",
    amount: 129.99,
    paymentStatus: "Paid",
    orderStatus: "Delivered",
    shippingAddress: "248 A Block, Street No 3, Laxmi Nagar, East Delhi, Delhi, 110092",
    trackingId: "TRK-GD2048-91",
    notes: "Delivered successfully to the customer's default address.",
  },
  {
    id: "GD-2049",
    customerName: "Aarav Mehta",
    customerEmail: "aarav.mehta@gmail.com",
    customerPhone: "+91 98765 12045",
    productName: "Classic White Sneakers",
    productCategory: "Shoes",
    quantity: 1,
    orderDate: "2026-06-02",
    deliveryDate: "2026-06-09",
    shippingMethod: "Standard Delivery",
    paymentMethod: "UPI",
    amount: 89.5,
    paymentStatus: "Paid",
    orderStatus: "Shipped",
    shippingAddress: "1202, Sea Crest Towers, Linking Road, Bandra West, Mumbai, 400050",
    trackingId: "TRK-GD2049-42",
    notes: "Package has left the fulfilment center.",
  },
  {
    id: "GD-2050",
    customerName: "Diya Sharma",
    customerEmail: "diya.sharma@gmail.com",
    customerPhone: "+91 98112 45320",
    productName: "Smart Watch Series X",
    productCategory: "Electronics",
    quantity: 1,
    orderDate: "2026-06-03",
    deliveryDate: "2026-06-12",
    shippingMethod: "Standard Delivery",
    paymentMethod: "Cash on Delivery",
    amount: 249.0,
    paymentStatus: "Pending",
    orderStatus: "Processing",
    shippingAddress: "45, Pink City Residency, MI Road, Ashok Nagar, Jaipur, 302001",
    trackingId: "TRK-GD2050-77",
    notes: "Payment will be collected on delivery.",
  },
  {
    id: "GD-2051",
    customerName: "Rohan Verma",
    customerEmail: "rohan.verma@gmail.com",
    customerPhone: "+91 90909 88442",
    productName: "Noise Cancelling Headphones",
    productCategory: "Electronics",
    quantity: 1,
    orderDate: "2026-05-29",
    deliveryDate: "2026-06-04",
    shippingMethod: "Express Delivery",
    paymentMethod: "Debit Card",
    amount: 189.99,
    paymentStatus: "Paid",
    orderStatus: "Out for Delivery",
    shippingAddress: "B-704, Riverdale Heights, Baner Road, Baner, Pune, 411045",
    trackingId: "TRK-GD2051-65",
    notes: "Courier is attempting delivery today.",
  },
  {
    id: "GD-2052",
    customerName: "Isha Kapoor",
    customerEmail: "isha.kapoor@gmail.com",
    customerPhone: "+91 99887 77125",
    productName: "Travel Backpack Pro",
    productCategory: "Accessories",
    quantity: 2,
    orderDate: "2026-05-28",
    deliveryDate: "2026-06-05",
    shippingMethod: "Standard Delivery",
    paymentMethod: "Wallet",
    amount: 59.99,
    paymentStatus: "Paid",
    orderStatus: "Pending",
    shippingAddress: "91, Rosewood Enclave, Madhya Marg, Sector 9, Chandigarh, 160009",
    trackingId: "TRK-GD2052-18",
    notes: "Awaiting warehouse confirmation.",
  },
  {
    id: "GD-2053",
    customerName: "Vivaan Rao",
    customerEmail: "vivaan.rao@gmail.com",
    customerPhone: "+91 94401 22448",
    productName: "Wireless Mechanical Keyboard",
    productCategory: "Electronics",
    quantity: 1,
    orderDate: "2026-05-24",
    deliveryDate: "2026-05-31",
    shippingMethod: "Standard Delivery",
    paymentMethod: "Credit Card",
    amount: 149.0,
    paymentStatus: "Refunded",
    orderStatus: "Returned",
    shippingAddress: "8-2-293, Lotus Court, Road No. 12, Banjara Hills, Hyderabad, 500034",
    trackingId: "TRK-GD2053-33",
    notes: "Customer returned the product and refund has been completed.",
  },
  {
    id: "GD-2054",
    customerName: "Ananya Nair",
    customerEmail: "ananya.nair@gmail.com",
    customerPhone: "+91 97444 18320",
    productName: "Smart Home Speaker",
    productCategory: "Electronics",
    quantity: 1,
    orderDate: "2026-05-21",
    deliveryDate: "2026-05-28",
    shippingMethod: "Standard Delivery",
    paymentMethod: "UPI",
    amount: 77.25,
    paymentStatus: "Paid",
    orderStatus: "Cancelled",
    shippingAddress: "22C, Palm Grove, Marine Drive, Ernakulam, Kochi, 682031",
    trackingId: "TRK-GD2054-29",
    notes: "Order was cancelled before dispatch.",
  },
  {
    id: "GD-2055",
    customerName: "Kabir Singh",
    customerEmail: "kabir.singh@gmail.com",
    customerPhone: "+91 96503 77890",
    productName: "Gaming Mouse Elite",
    productCategory: "Electronics",
    quantity: 1,
    orderDate: "2026-05-19",
    deliveryDate: "2026-05-27",
    shippingMethod: "Express Delivery",
    paymentMethod: "Credit Card",
    amount: 45.0,
    paymentStatus: "Paid",
    orderStatus: "Delivered",
    shippingAddress: "17, Awadh Apartments, Hazratganj Road, Hazratganj, Lucknow, 226001",
    trackingId: "TRK-GD2055-54",
    notes: "Delivered and closed.",
  },
  {
    id: "GD-2056",
    customerName: "Meera Joshi",
    customerEmail: "meera.joshi@gmail.com",
    customerPhone: "+91 98220 54110",
    productName: "Bluetooth Speaker Mini",
    productCategory: "Electronics",
    quantity: 1,
    orderDate: "2026-06-04",
    deliveryDate: "2026-06-10",
    shippingMethod: "Standard Delivery",
    paymentMethod: "Cash on Delivery",
    amount: 35.5,
    paymentStatus: "Pending",
    orderStatus: "Processing",
    shippingAddress: "304, Saffron Heights, CG Road, Navrangpura, Ahmedabad, 380009",
    trackingId: "TRK-GD2056-88",
    notes: "Order is being packed.",
  },
  {
    id: "GD-2057",
    customerName: "Arjun Das",
    customerEmail: "arjun.das@gmail.com",
    customerPhone: "+91 93302 45117",
    productName: "Cotton Hoodie Set",
    productCategory: "Fashion",
    quantity: 2,
    orderDate: "2026-06-05",
    deliveryDate: "2026-06-13",
    shippingMethod: "Standard Delivery",
    paymentMethod: "UPI",
    amount: 72.0,
    paymentStatus: "Paid",
    orderStatus: "Pending",
    shippingAddress: "5A, Victoria Residency, Park Street, Taltala, Kolkata, 700016",
    trackingId: "TRK-GD2057-26",
    notes: "Awaiting dispatch slot.",
  },
];

export function getOrderById(orderId) {
  return orderData.find((order) => String(order.id) === String(orderId)) || orderData[0];
}
