export const userProfiles = [
  {
    id: 1,
    fullName: "Karan Chandra Kothari",
    emailAddress: "kotharikaran07@gmail.com",
    mobileNumber: "+91 92679 33722",
    language: "English",
    timezone: "GMT+5:30 (IST)",
    bio: "Frontend developer and web design enthusiast. Building beautiful interfaces for modern applications using HTML, CSS, JavaScript and React using modern techniques.",
    dateOfBirth: "2007-08-10",
    gender: "Male",
    accountCreatedDate: "2025-01-01",
    houseFlatNo: "248 A Block",
    buildingApartmentName: "Street No 3",
    streetRoadName: "Laxmi Nagar",
    areaLocalityColony: "East Delhi",
    landmark: "",
    cityTownVillage: "Delhi",
    state: "Delhi",
    country: "India",
    pinCode: "110092",
    orders: 128,
    status: "Verified",
    joined: "Jan 01, 2025",
  },
  {
    id: 2,
    fullName: "Aarav Mehta",
    emailAddress: "aarav.mehta@gmail.com",
    mobileNumber: "+91 98765 12045",
    language: "English",
    timezone: "GMT+5:30 (IST)",
    bio: "Frequent buyer with a focus on premium accessories, leather goods, and seasonal fashion collections.",
    dateOfBirth: "1996-02-14",
    gender: "Male",
    accountCreatedDate: "2025-02-14",
    houseFlatNo: "1202",
    buildingApartmentName: "Sea Crest Towers",
    streetRoadName: "Linking Road",
    areaLocalityColony: "Bandra West",
    landmark: "Near National College",
    cityTownVillage: "Mumbai",
    state: "Maharashtra",
    country: "India",
    pinCode: "400050",
    orders: 84,
    status: "Active",
    joined: "Feb 14, 2025",
  },
  {
    id: 3,
    fullName: "Diya Sharma",
    emailAddress: "diya.sharma@gmail.com",
    mobileNumber: "+91 98112 45320",
    language: "Hindi",
    timezone: "GMT+5:30 (IST)",
    bio: "Verified customer interested in ethnic wear, home decor, and festival gifting collections.",
    dateOfBirth: "1998-09-21",
    gender: "Female",
    accountCreatedDate: "2025-03-03",
    houseFlatNo: "45",
    buildingApartmentName: "Pink City Residency",
    streetRoadName: "MI Road",
    areaLocalityColony: "Ashok Nagar",
    landmark: "Opposite Central Park",
    cityTownVillage: "Jaipur",
    state: "Rajasthan",
    country: "India",
    pinCode: "302001",
    orders: 63,
    status: "Verified",
    joined: "Mar 03, 2025",
  },
  {
    id: 4,
    fullName: "Rohan Verma",
    emailAddress: "rohan.verma@gmail.com",
    mobileNumber: "+91 90909 88442",
    language: "English",
    timezone: "GMT+5:30 (IST)",
    bio: "Active account with repeat purchases across electronics, footwear, and everyday essentials.",
    dateOfBirth: "1994-11-08",
    gender: "Male",
    accountCreatedDate: "2025-03-26",
    houseFlatNo: "B-704",
    buildingApartmentName: "Riverdale Heights",
    streetRoadName: "Baner Road",
    areaLocalityColony: "Baner",
    landmark: "Near High Street",
    cityTownVillage: "Pune",
    state: "Maharashtra",
    country: "India",
    pinCode: "411045",
    orders: 41,
    status: "Active",
    joined: "Mar 26, 2025",
  },
  {
    id: 5,
    fullName: "Isha Kapoor",
    emailAddress: "isha.kapoor@gmail.com",
    mobileNumber: "+91 99887 77125",
    language: "English",
    timezone: "GMT+5:30 (IST)",
    bio: "Verified user with strong engagement in luxury handbags, apparel drops, and coupon campaigns.",
    dateOfBirth: "1997-05-17",
    gender: "Female",
    accountCreatedDate: "2025-04-08",
    houseFlatNo: "91",
    buildingApartmentName: "Rosewood Enclave",
    streetRoadName: "Madhya Marg",
    areaLocalityColony: "Sector 9",
    landmark: "Near Leisure Valley",
    cityTownVillage: "Chandigarh",
    state: "Chandigarh",
    country: "India",
    pinCode: "160009",
    orders: 92,
    status: "Verified",
    joined: "Apr 08, 2025",
  },
  {
    id: 6,
    fullName: "Vivaan Rao",
    emailAddress: "vivaan.rao@gmail.com",
    mobileNumber: "+91 94401 22448",
    language: "English",
    timezone: "GMT+5:30 (IST)",
    bio: "Active customer browsing electronics, smart watches, headphones, and performance accessories.",
    dateOfBirth: "1995-07-12",
    gender: "Male",
    accountCreatedDate: "2025-04-19",
    houseFlatNo: "8-2-293",
    buildingApartmentName: "Lotus Court",
    streetRoadName: "Road No. 12",
    areaLocalityColony: "Banjara Hills",
    landmark: "Near KBR Park",
    cityTownVillage: "Hyderabad",
    state: "Telangana",
    country: "India",
    pinCode: "500034",
    orders: 36,
    status: "Active",
    joined: "Apr 19, 2025",
  },
  {
    id: 7,
    fullName: "Ananya Nair",
    emailAddress: "ananya.nair@gmail.com",
    mobileNumber: "+91 97444 18320",
    language: "English",
    timezone: "GMT+5:30 (IST)",
    bio: "Verified user who regularly orders footwear, apparel, and wishlist restock products.",
    dateOfBirth: "1999-03-28",
    gender: "Female",
    accountCreatedDate: "2025-05-02",
    houseFlatNo: "22C",
    buildingApartmentName: "Palm Grove",
    streetRoadName: "Marine Drive",
    areaLocalityColony: "Ernakulam",
    landmark: "Near Rainbow Bridge",
    cityTownVillage: "Kochi",
    state: "Kerala",
    country: "India",
    pinCode: "682031",
    orders: 57,
    status: "Verified",
    joined: "May 02, 2025",
  },
  {
    id: 8,
    fullName: "Kabir Singh",
    emailAddress: "kabir.singh@gmail.com",
    mobileNumber: "+91 96503 77890",
    language: "Hindi",
    timezone: "GMT+5:30 (IST)",
    bio: "Pending verification account with recent interest in menswear, wallets, caps, and sale events.",
    dateOfBirth: "1993-12-04",
    gender: "Male",
    accountCreatedDate: "2025-05-18",
    houseFlatNo: "17",
    buildingApartmentName: "Awadh Apartments",
    streetRoadName: "Hazratganj Road",
    areaLocalityColony: "Hazratganj",
    landmark: "Near GPO",
    cityTownVillage: "Lucknow",
    state: "Uttar Pradesh",
    country: "India",
    pinCode: "226001",
    orders: 22,
    status: "Pending",
    joined: "May 18, 2025",
  },
  {
    id: 9,
    fullName: "Meera Joshi",
    emailAddress: "meera.joshi@gmail.com",
    mobileNumber: "+91 98220 54110",
    language: "English",
    timezone: "GMT+5:30 (IST)",
    bio: "Verified buyer with consistent purchases in sunglasses, fashion basics, and gifting items.",
    dateOfBirth: "1992-06-18",
    gender: "Female",
    accountCreatedDate: "2025-06-06",
    houseFlatNo: "304",
    buildingApartmentName: "Saffron Heights",
    streetRoadName: "CG Road",
    areaLocalityColony: "Navrangpura",
    landmark: "Near Municipal Market",
    cityTownVillage: "Ahmedabad",
    state: "Gujarat",
    country: "India",
    pinCode: "380009",
    orders: 74,
    status: "Verified",
    joined: "Jun 06, 2025",
  },
  {
    id: 10,
    fullName: "Arjun Das",
    emailAddress: "arjun.das@gmail.com",
    mobileNumber: "+91 93302 45117",
    language: "English",
    timezone: "GMT+5:30 (IST)",
    bio: "Active customer purchasing shoes, watches, and curated product bundles from seasonal campaigns.",
    dateOfBirth: "1991-01-30",
    gender: "Male",
    accountCreatedDate: "2025-08-24",
    houseFlatNo: "5A",
    buildingApartmentName: "Victoria Residency",
    streetRoadName: "Park Street",
    areaLocalityColony: "Taltala",
    landmark: "Near Assembly of God Church",
    cityTownVillage: "Kolkata",
    state: "West Bengal",
    country: "India",
    pinCode: "700016",
    orders: 49,
    status: "Active",
    joined: "Aug 24, 2025",
  },
];

export function getUserProfileById(userId) {
  return userProfiles.find((user) => String(user.id) === String(userId)) || userProfiles[0];
}
